// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmV-2sueG_DLZRav-stnRxX7mq3adiOMM',
    appId: '1:636775501231:web:a06bf11654ef9faff2f35a',
    messagingSenderId: '636775501231',
    projectId: 'booklub-8e557',
    authDomain: 'booklub-8e557.firebaseapp.com',
    storageBucket: 'booklub-8e557.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5U7mG-W1RJx07VO9g9iHClMXw0AwokNQ',
    appId: '1:636775501231:android:49a9e6118e7d0c4af2f35a',
    messagingSenderId: '636775501231',
    projectId: 'booklub-8e557',
    storageBucket: 'booklub-8e557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrr_WCuP-W1XHi53rIlWpRS5ZqrpFDjh0',
    appId: '1:636775501231:ios:cc7a7ac06f18f455f2f35a',
    messagingSenderId: '636775501231',
    projectId: 'booklub-8e557',
    storageBucket: 'booklub-8e557.appspot.com',
    iosClientId: '636775501231-0ofuvqnm0vl0fh0kv0iikm21bbt85342.apps.googleusercontent.com',
    iosBundleId: 'com.example.booklub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrr_WCuP-W1XHi53rIlWpRS5ZqrpFDjh0',
    appId: '1:636775501231:ios:cc7a7ac06f18f455f2f35a',
    messagingSenderId: '636775501231',
    projectId: 'booklub-8e557',
    storageBucket: 'booklub-8e557.appspot.com',
    iosClientId: '636775501231-0ofuvqnm0vl0fh0kv0iikm21bbt85342.apps.googleusercontent.com',
    iosBundleId: 'com.example.booklub',
  );
}
